### ISSUE TITLE
Idesk changing pid after icon's application execution

### ISSUE THREAD

**Issue by giovannitarter** [neagix/idesk#2]
Hi.
Not really an issue, I am trying to understand the design reason behind this behaviour that seems to be troublesome in my use case.

Here the problem:
When idesk executes the command specified with line Command[0] in an icon descriptor file, the process is executed replacing the idesk process image instead of the child process image.

Please see line:
https://github.com/neagix/idesk/blob/df7c7e9343ced7c8bcdc0bc50f75d7a15e1af03b/src/XDesktopContainer.cpp#L589 
The execl call (the one which executes the new process replacing the process image) is invoked on the process where the fork() call did not return 0, hence the parent process.

Idesk process is replaced by the new process  but keeps running on the child process changing its pid.
Moreover, if any process was waiting for idesk to die (i.e. with a wait in a bash script), the wait ends as soon as the newly spawned process ends (but idesk is still running!). 

Is it a bug or a precise design choice?
Are there any benefits?

**Comment by neagix** [comment]
@giovannitarter I cannot tell precisely as that code comes from the original author: https://github.com/neagix/idesk/commit/f39722e52722eb666bdd622de34f329cc9d7b204

That check is already incorrect because it's not checking for negative values; aside from that, I think it's a bug because the comment says `Primer proceso hijo` == `first child process` and there is below another comment `exit fork`.

The idea was probably to wait for the command (run in the child fork) to complete execution, so the condition should be changed to `if (pid=fork() == 0)` in order for that to work.

In its current version it is replacing the parent PID with the `execl` process, so that's not going to bring any benefit.

**Comment by neagix** [comment]
@giovannitarter can you please test if latest commit 4dcd1c2 fixes the issue?

**Comment by giovannitarter** [comment]
The issue is fixed.

Thanks,
Giovanni

Il giorno lun 13 gen 2020 alle ore 14:55 Nea Gix <notifications@github.com>
ha scritto:
